export const LOGIN ="LOGIN";
export const REGISTER="REGISTER";
export const CALL_LIST_ACCOUNT="CALL_LIST_ACCOUNT";
export const FETCH_TASK_SUCCESS="FETCH_TASK_SUCCESS";








//////
export const SHOWINFOR= "SHOWINFOR";

export const THONGBAO ="THONGBAO";
export const TAIKHOAN ="TAIKHOAN";

export const DANGXUAT ="DANGXUAT";
export const THONG_TIN_LEAD="THONG_TIN_LEAD";

export const OPEN_FORM_DIALOG ="OPEN_FORM_DIALOG";
export const CLOSE_FORM_DIALOG ="CLOSE_FORM_DIALOG";
export const GET_DATA__DID_LOGIN="GET_DATA__DID_LOGIN";
export const GET_DATA__DID_LOGIN_SUCCESS="GET_DATA__DID_LOGIN_SUCCESS";
export const GET_DATA__DID_LOGIN_FAILD="GET_DATA__DID_LOGIN_FAILD";
export const OPEN_SHOW_INFO_DID_LOGIN="OPEN_SHOW_INFO_DID_LOGIN";
export const CLOSE_SHOW_INFO_DID_LOGIN="CLOSE_SHOW_INFO_DID_LOGIN";
export const SHOW_INFOR_DID_LOGIN="SHOW_INFOR_DID_LOGIN";
export const BUY_LEAD="BUY_LEAD";
export const UPDATE="UPDATE";
export const SENT_DATA_LOAN="SENT_DATA_LOAN";
export const THONG_TIN_CHUNG ="THONG_TIN_CHUNG";
export const GET_THONG_TIN_CHUNG ="GET_THONG_TIN_CHUNG";
export const FET_CHANGE_PASS= "FET_CHANGE_PASS";
export const FET_CHANGE_PASS_SUCCESS= "FET_CHANGE_PASS_SUCCESS";
export const FET_CHANGE_PASS_FAID= "FET_CHANGE_PASS_FAID";
